photoshop:
  dir: /Users/sb2/dreamkeepers-psd
  deck: Template009.1.psd
  non_deck: Template009.1h.psd
database:
  dir: /Users/sb2/dreamkeepers-dat
  host: www.epfgames.com
  port: 5432
  name: skirmish
  user: guest
  ssl: false
